require("lib.evil.volume")
require("lib.evil.battery")
require("lib.evil.cpu")
require("lib.evil.temperature")
require("lib.evil.ram")
require("lib.evil.weather")
require("lib.evil.mpd")
require("lib.evil.brightness")
-- -- require("lib.evil.spotify")
