---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by evmenov.
--- DateTime: 11/24/21 12:59 PM
---

local awful = require("awful")

client.connect_signal("manage", function(c)
    if not awesome.startup then
        awful.client.setslave(c)
    end

    if awesome.startup and not c.size_hints.user_position and not c.size_hints.program_position then
        awful.placement.no_offscreen(c)
    end
end)
