---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by evmenov.
--- DateTime: 11/24/21 12:58 PM
---

local awful     = require("awful")
local beautiful = require("beautiful")

tag.connect_signal("property::layout", function(t)
    local current_layout = awful.tag.getproperty(t, "layout")

    if (current_layout == awful.layout.suit.max) then
        t.gap = 0
    else
        t.gap = beautiful.useless_gap
    end
end)

tag.connect_signal("request::screen", function(t)
    local fallback_tag = nil

    -- find tag with same name on any other screen
    for other_screen in screen do
        fallback_tag = awful.tag.find_by_name(other_screen, t.name)
        if fallback_tag ~= nil then
            break
        end
    end

    -- no tag with same name exists, chose random one
    if fallback_tag == nil then
        fallback_tag = awful.tag.find_fallback()
    end

    -- delete the tag and move it to other screen
    t:delete(fallback_tag, true)
end)
