---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by evmenov.
--- DateTime: 10.09.21 11:01
---

-- https://codepen.io/havardob/pen/YzwzQgm
-- или
-- https://codepen.io/simeydotme/pen/oNwgpGR