---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hp-envy-x360-15-ee0020nn.
--- DateTime: 8/31/21 12:57 PM
---

wibox.layout.align
wibox.layout.fixed
wibox.layout.flex
wibox.layout.grid
wibox.layout.manual
wibox.layout.ratio
wibox.layout.stack